pipeline {
    agent any
	
    stages {
        stage('build nodejs') {
            steps {
                script {
                sh """
	          npm install express		
		  npm start
                  """
		    
                }
            }
        }
    }
}
